<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>IdentityProviderDemo</AssemblyName>
    <RootNamespace>IdentityProviderDemo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\dk.nita.saml20\Identity.Saml.csproj" />
  </ItemGroup>

</Project>